### ISSUE TITLE
Extract tasks into separate packages

### ISSUE THREAD

**Issue by backflip** [unic/estatico-nou#2]
# Tasks
- [x] `js`: https://github.com/unic/estatico/blob/develop/gulp/js/default.js (include `preset-env`, check out HMR)
- [x] `js:lint` (based on `eslint`, add `fix` option)
- [x] `js:modernizr`: https://github.com/unic/estatico/blob/develop/gulp/js/modernizr.js (possibly replace with Webpack loader instead)
- [x] `js:test`: Based on Puppeter and QUnit (for now): https://github.com/jonkemp/gulp-qunit/issues/31#issuecomment-347005021
- [x] `js:mocks`: https://github.com/unic/estatico/blob/develop/gulp/js/mocks.js
- [x] `css`: https://github.com/unic/estatico/blob/develop/gulp/css/default.js → compare to webpack afterwards @alinamelnyk 
- [x] `css:lint` (based on `sass-lint` or `stylelint`) @Wymowny 
- [x] `css:colors`: Probably replace with https://github.com/Updater/node-sass-json-importer
- [x] `css:fonts`: https://github.com/unic/estatico/blob/develop/gulp/css/fonts.js @orioltf 
- [x] `media:svgsprite`: https://github.com/unic/estatico/blob/develop/gulp/media/svgsprite.js @drowka 
- [ ] [low prio] `media:iconfont`: https://github.com/unic/estatico/blob/develop/gulp/media/iconfont.js
- [ ] [low prio] `media:dataurls`: Data URIs: https://github.com/unic/estatico/blob/develop/gulp/media/dataurls.js
- [x] `media:imageversions`: https://github.com/unic/estatico/blob/develop/gulp/media/imageversions.js
- [x] `media:copy`: Make more generic (not bound to media files): https://github.com/unic/estatico/blob/develop/gulp/media/copy.js
- [x] `scaffold`: Evaluate https://github.com/amwmedia/plop and Yeoman, e.g.
- [x] `serve`: Based on `browsersync`
- [x] `watch` (with proper dependency graph)
- [x] `document`: Replace with proper READMEs for every task

# Examples:
* [See existing packages](../packages/)

# Criteria:
* [Exporting plugin factory](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L262)
  * Taking options overwriting defaults as argument. Defaults for a "standard" gulp task:
    * [`src`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L45): Which files to read
    * [`srcBase`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L46): See [docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase)
    * [`dest`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L47): Where to write to
    * [`watch`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L48): Which files should trigger a rebuild
    * [`plugins`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L49-L90): Passed to specific gulp plugins
    * [`logger`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L91): Used for infos, debugging and errors. Most probably an instance of [estatico-utils](https://github.com/unic/estatico-nou/tree/master/packages/estatico-utils)'s `Logger`
  * Exposing options for everything configurable. Setting plugin options to `null` should [disable the corresponding step](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L166)
  * Returning a gulp stream in case of "standard" gulp tasks. Most probably returning a promise otherwise since we don't want to deal with callbacks.
  * Using [`gulp-plumber`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L146) to prevent stream from unpiping, adding [`.on('error', err => config.logger.error(err, env.dev))`](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L175) to every step possibly throwing.
  * Using [`joi`]() to validate options: https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/index.js#L9-L37
* Using [gulp 4](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/package.json#L15) (if using gulp). Probably not having an effect on "standard gulp tasks since they mostly use `gulp.src` and `gulp.dest` which [should not break anything for us](https://github.com/gulpjs/gulp/blob/4.0/CHANGELOG.md#400)
* Not using `gulp-util` which will be deprecated. Rather rely on the underlying modules (`plugin-error`, `fancy-log`, `chalk`, `minimist` etc.
* Documenting usage and options in [README.md](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/README.md)
* Adding [tests](https://github.com/unic/estatico-nou/blob/master/packages/estatico-handlebars/test/index.js)

**Comment by backflip** [comment]
@christiansany / @lbsonley: Moved to https://github.com/unic/estatico-nou/issues/3
