### ISSUE TITLE
[boilerplate] JS architecture

### ISSUE THREAD

**Issue by backflip** [unic/estatico-nou#3]
- Establish the new way of writing JavaScript in collaboration with other Frontend Developers.
- Restructure the whole Estatico JS initiation logic into separate NPM packages.
- Add a more reusable way of writing JS (factory/composition).
- Give a good documentation on what changed in the architecture and how developers can adapt.
- Establish a checklist for JS Modules/Factories/Composites
- Establish backward-compatibility for at least IE(X)

### Factory/Composition

**Examples**
* Factory: https://www.npmjs.com/package/@unic/factory-breakpoint-manager
* Composite: https://www.npmjs.com/package/@unic/composite-observer

**Generators**
* Composite: https://www.npmjs.com/package/generator-composite

### TODO
- [x] Use Apache license, Unic is the author
- [ ] Make a workshop and discuss the proposition of factory/composition

### Components
- [ ] `composite-logger`  
https://github.com/unic/estatico/blob/develop/source/assets/js/helpers/helper.js#L18-L30
- [ ] `ui-extend`  
https://github.com/unic/estatico/blob/develop/source/assets/js/helpers/helper.js#L42-L56
- [ ] `ui-pretty-events`  
Completely new thingie

### Notes
- [ ] Enable better debugging inside of Modules/Components Better debugging?
- [ ] Proper automatic documentation of components (JSdoc)  
https://github.com/jsdoc3/jsdoc

**Comment by christiansany** [comment]
UPDATE:
I've created a repository for collecting small modules and easily have them published on npm.
With this lerna-repository, a few things like the composite generator are obsolete and no longer needed. I'll discuss the changes with @lbsonley and then Change the Issue-description. (Since, we have another repo, issues/todos will be tracked in the designated repository. This Issue will only be used, to track the general progress)
https://github.com/unic/javascript-packages
